version: "3.7"

services:

  php-apache:
    image: webdevops/php-apache
    container_name: php-apache
    links:
      - "mariadb"
    ports:
      - 8080:80
    volumes:
      - "./:/app:z"
    environment:
      - PMA_ARBITRARY=1
      - PHP_DISPLAY_ERRORS=On
    restart: unless-stopped

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb-vol:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    links:
      - "mariadb"
    ports:
      - 8081:80
    volumes:
      - pma-vol:/var/lib/mysql:z
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=mariadb
    restart: unless-stopped



volumes:
  mariadb-vol:
  pma-vol:
